import "./globals.css";
import type { Metadata } from "next";
import LocalFont from "next/font/local";

const meticula = LocalFont({ src: "../fonts/meticula.ttf" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={meticula.className}>{children}</body>
    </html>
  );
}
